server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 111111

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rht.springcloud.entities