server:
  port: 80

spring:
  application:
    name: cloud-consumer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 111111

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rht.springcloud.entities

eureka:
  client:
    #true表示不向注册中心注册自己
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能搭配ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址 查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/